# /etc/nixos/home.nix
# { config, pkgs, lib, inputs, ... }:
{ config, pkgs, lib, ... }:
let
  cline = pkgs.vscode-utils.buildVscodeMarketplaceExtension {
    mktplcRef = {
      name = "claude-dev";
      publisher = "saoudrizwan";
      version = "4.0.6";
      hash = "sha256-Bj/LYDPv5grQc1S0+gGid55Gfhd2QexIC9nro1oy3Eg=";
    };
  };
in
{
  home.stateVersion = "25.11";
  home.username = "chouette";
  home.homeDirectory = "/home/chouette";

  imports = [
    ./modules/neovim
  ];

  # SSH鍵の設定（sourceを使用）
  home.file = {
    ".ssh/id_ed25519.pub" = {
      source = ./secrets/id_ed25519.pub;
      force = true;
    };
    ".ssh/config" = {
      text = ''
      Host github.com
        HostName github.com
        Port 22
        User git
      Host u2604C
        HostName 10.231.221.222
        User chouette
      Host u2404D
        HostName 10.231.221.162
        User chouette
      Host *
        Port 9978
        IdentityFile ~/.ssh/id_ed25519
        IdentitiesOnly yes
        ServerAliveInterval 60
        ServerAliveCountMax 3
      '';
      force = true;
    };
  };

  # Xhostでローカルアクセスを許可する.desktopファイルを作成する
  xdg.configFile."autostart/xhost-local.desktop".text = ''
  [Desktop Entry]
  Type=Application
  Name=Xhost Local Allow
# Exec=${pkgs.xorg.xhost}/bin/xhost +local:
  Exec=${pkgs.xhost}/bin/xhost +local:
  Terminal=false
  X-KDE-AutostartScript=true
  '';


  # 秘密鍵の復号化をactivationScriptで実行
  home.activation = {
    decryptSSHKey = lib.hm.dag.entryAfter ["writeBoundary"] ''
      # age鍵が存在する場合のみ復号化を実行
      if [ -f "${config.home.homeDirectory}/.config/age/key.txt" ]; then
        ${pkgs.age}/bin/age -d \
          -i "${config.home.homeDirectory}/.config/age/key.txt" \
          -o "${config.home.homeDirectory}/.ssh/id_ed25519" \
          "${config.home.homeDirectory}/NixOS-nixos/secrets/id_ed25519.age"
        
        chmod 600 "${config.home.homeDirectory}/.ssh/id_ed25519"

        echo "SSH private key decrypted successfully"
      else
        echo "Warning: age key not found at ~/.config/age/key.txt"
        echo "Please decrypt manually:"
        echo "  age -d -i ~/.config/age/key.txt -o ~/.ssh/id_ed25519 ~/NixOS-nixos/secrets/id_ed25519.age"
      fi
    '';
  };

  # 権限設定
  systemd.user.tmpfiles.rules = [
    "f /home/chouette/.ssh/id_ed25519 0600 - - - -"
    "f /home/chouette/.ssh/config 0600 - - - -"
  ];

  programs.direnv.enable = true;

  /*
  programs.google-chrome = {
    enable = true;
    commandLineArgs = [
      "--ozone-platform-hint=auto"
      "--enable-features=WaylandWindowDecorations"
      # もしこれでダメなら、一時的にGPUを無効化して検証
      # "--disable-gpu" 

      # "--ozone-platform=wayland --enable-wayland-ime"
    ];
  };
  */

  programs.google-chrome = {
    enable = true;
    commandLineArgs = [
      "--ozone-platform-hint=auto"
    ];
  };

  # Cline (Claude Dev) を Marketplace から宣言的に取得
  # version は Marketplace の itemName を確認して更新します。

  programs.vscode = {
    enable = true;
    package = pkgs.vscode;
    profiles.default = {
      extensions = with pkgs.vscode-extensions; [
        golang.go
        mhutchie.git-graph
        ms-ceintl.vscode-language-pack-ja
        vscodevim.vim
        jnoortheen.nix-ide
        ms-vscode-remote.remote-ssh
        cline
      # liemlb.nix-flakes
      ];
      userSettings = {
        # テーマ設定
      # "workbench.colorTheme" = "Monokai Dimmed";
        "workbench.colorTheme" = "Monokai";
      # "workbench.colorTheme" = "Tomorrow Night Blue";
        "go.toolsManagement.autoUpdate" = false;
        "diffEditor.ignoreTrimWhitespace" = false;
        "go.alternateTools" = {
          "gopls" = "/run/current-system/sw/bin/gopls";
          "dlv" = "/run/current-system/sw/bin/dlv";
        };
        # 以下、必要に応じて他の設定
        "git.autofetch" = true;
        "github.copilot.nextEditSuggestions.enabled" = true;
        "editor.editContext" = false;
        "files.autoSave" = "afterDelay";
        "nix.enableLanguageServer" = true;
        "nix.serverPath" = "nixd";
        # nix-ide拡張機能にnixdを使うよう指定（重要）
        "nix.serverSettings" = {
          "nixd" = {
            "formatting" = {
              "command" = [ "nixpkgs-fmt" ]; # フォーマッタを使う場合
            };
          };
        };
        # Cline の API 設定は拡張機能内部の Secret Storage に保存されるため、
        # userSettings への平文記述は不要です。
      };
    };
  };
# }

# wayland.windowManager.hyprland = {
#   enable = true;
#   settings = {
#     # 警告を消す
#     autogenerated = 0; 

#     # キーバインド設定
#     "$mod" = "SUPER";
#     bind = [
#       "$mod, Q, exec, konsole" # kittyの代わりにPlasmaのkonsoleを使う例
#       "$mod, M, exit,"
#       "$mod, E, exec, dolphin"
#       "$mod, V, togglefloating,"
#       "$mod, R, exec, wofi --show drun" # ランチャー（別途インストールが必要）
#      ];
      
#     # モニター設定（解像度やリフレッシュレート）
#     monitor = [
#       ",preferred,auto,1"
#     ];
#   };
# };

  # Git設定
  programs.git = {
    enable = true;
    settings = {
      user.name = "Chouette2100";
      user.email = "your-email@example.com";
      init.defaultBranch = "main";
      pull.rebase = false;
    };
  };

  # SSHエージェント
  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;
  # matchBlocks = {
    settings = {
      "*" = {
        forwardAgent = true;
      };
    };
  };

  # Bash設定
  programs.bash = {
    enable = true;
    shellAliases = {
      ll = "ls -la";
      update = "sudo nixos-rebuild switch --flake /etc/nixos#nixos";
      rebuild = "sudo nixos-rebuild switch --flake /etc/nixos#nixos";
      testbuild = "sudo nixos-rebuild test --flake /etc/nixos#nixos";
      bootbuild = "sudo nixos-rebuild boot --flake /etc/nixos#nixos";
      clean = "sudo nix-collect-garbage -d";
      nixcheck = "nix flake check /home/chouette/NixOS-nixos";

      dbx-start = "systemctl --user start dropbox-mount";
      dbx-stop = "systemctl --user stop dropbox-mount";
      dbx-restart = "systemctl --user restart dropbox-mount";
      dbx-status = "systemctl --user status dropbox-mount";
      dbx-log = "journalctl --user -u dropbox-mount -n 200 --no-pager";
      dbx-logf = "journalctl --user -u dropbox-mount -f";
      dbx-unmount = "fusermount -u /home/chouette/Dropbox";

      pwhash = "openssl passwd -6";
      myip = "ip -br a";
    };
    
    initExtra = ''
      export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
      
      if [ -z "$SSH_AUTH_SOCK" ]; then
        eval "$(ssh-agent -s)" > /dev/null
      fi
    '';
  };

  xdg.configFile."kscreenlockerrc".text = ''
    [Daemon]
    Autolock=false
    LockOnStartup=false
  '';

  # fcitx5 トリガーキーを半角/全角キーに設定
  xdg.configFile."fcitx5/config".force = true;
  xdg.configFile."fcitx5/config".text = ''
    [Hotkey]
    TriggerKeys=Zenkaku_Hankaku

    [Hotkey/TriggerKeys]
    0=Zenkaku_Hankaku
  '';

  xdg.configFile."kxkbrc".text = ''
    [Layout]
    DisplayNames=
    LayoutList=jp
    Model=jp106
    Options=
    ResetOldOptions=true
    ShowFlag=false
    SwitchMode=WinClass
    Use=true
    VariantList=
  '';

  xdg.configFile."autostart/setxkbmap-jp.desktop".text = ''
    [Desktop Entry]
    Type=Application
    Name=Set XKB to JP106
    Exec=${pkgs.setxkbmap}/bin/setxkbmap -model jp106 -layout jp
    X-GNOME-Autostart-enabled=true
    X-KDE-autostart-after=panel
    NoDisplay=true
  '';

  # terminator
  xdg.configFile."autostart/terminator.desktop".text = ''
    [Desktop Entry]
    Type=Application
    Name=Terminator Autostart
    Comment=Start terminator with specific layout
    Exec=terminator --layout=new
    Terminal=false
    Categories=System;TerminalEmulator;
    X-GNOME-Autostart-enabled=true
  '';

systemd.user.services.dropbox-mount = {
  Unit = {
    Description = "Dropbox mount (rclone)";
    After = [ "network-online.target" ];
    Wants = [ "network-online.target" ];
  };

  Service = {
    Type = "simple";
    ExecStart = ''
      ${pkgs.rclone}/bin/rclone mount dropbox: %h/Dropbox \
        --config=/home/chouette/.config/rclone/rclone.conf \
        --vfs-cache-mode writes
    '';
    ExecStop = "/run/current-system/sw/bin/fusermount -u /home/chouette/Dropbox";
    Restart = "on-failure";
    RestartSec = "10s";
    ExecStartPre = "/run/current-system/sw/bin/mkdir -p /home/chouette/Dropbox";
  };

  Install = {
    WantedBy = [ "default.target" ];
  };
};


  # 便利なパッケージ
  home.packages = with pkgs; [
    # オフィス
    libreoffice-fresh
    hunspell        # スペルチェック
    hunspellDicts.en_US
    pdfarranger
    
    # クリエイティブ
    gimp
    inkscape
    vlc             # 動画再生

    # vsocde拡張機能で必要なコマンド
    nixd
    nixpkgs-fmt

    # neovim
    tmux
    htop
    tree
    ripgrep
    fzf
    bat
    wget
    curl
    unzip
    jq
# # 元の google-chrome を上書きする
# (google-chrome.overrideAttrs (old: {
#   installPhase = old.installPhase + ''
#     wrapProgram $out/bin/google-chrome-stable \
#       --add-flags "--ozone-platform=wayland --enable-wayland-ime"
#   '';
# }))
  ];
}
